spring:
  datasource:
    url: "jdbc:postgresql://postgres-auth:5432/authdb"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  flyway:
    validate-on-migrate: true
    enabled: true
    locations: "classpath:db/migration"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${G_CLIENT_ID}"
            client-secret: "${G_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:23000/auth-server/login/oauth2/code/google"

  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: update-user-data
      auto-offset-reset: earliest

logging:
  level:
    org.flywaydb: INFO
    org.apache.kafka: OFF
    org.springframework.kafka: OFF
    org.apache.zookeeper: OFF

server:
  servlet:
    context-path: /auth-server
  port: 2300

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

resend:
  api:
    key: "${RESEND_API_KEY}"
    url: "https://api.resend.com/emails"
  sender: "${RESEND_EMAIL}"
